package br.gov.frameworkdemoiselle.prodepa.queryfilter.annotations.metadata;

public enum OrConditionType {

  EQUAL,
  NOT_EQUAL;
  /*GT,       STRING_GREATER_THAN, CALENDAR_GREATER_THAN, DATE_GREATER_THAN,
  GE,       STRING_GREATER_OR_EQUAL_TO, CALENDAR_GREATER_OR_EQUAL_TO, DATE_GREATER_OR_EQUAL_TO,
  LT,       STRING_LESS_THAN, CALENDAR_LESS_THAN, DATE_LESS_THAN,
  LE,       STRING_LESS_OR_EQUAL_TO, CALENDAR_LESS_OR_EQUAL_TO, DATE_LESS_OR_EQUAL_TO,
  BETWEEN,  STRING_BETWEEN, DATE_BETWEEN, CALENDAR_BETWEEN,
  IS_NULL, IS_NOT_NULL,
  LIST_IS_EMPTY, LIST_IS_NOT_EMPTY, SET_IS_EMPTY, SET_IS_NOT_EMPTY, COLLECTION_IS_EMPTY, COLLECTION_IS_NOT_EMPTY,
  STRING_LIKE, STRING_NOT_LIKE, STRING_LIKE_STARTS_WITH, STRING_LIKE_ENDS_WITH,
  STRING_IN;*/
  
}
