/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.gov.demoiselle.portal.evento.model.impl;

import br.gov.demoiselle.portal.evento.model.EventoParticipante;
import br.gov.demoiselle.portal.evento.model.EventoParticipanteModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EventoParticipante service. Represents a row in the &quot;demoiselle_EventoParticipante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.gov.demoiselle.portal.evento.model.EventoParticipanteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventoParticipanteImpl}.
 * </p>
 *
 * @author Clovis Lemes Ferreira Junior
 * @see EventoParticipanteImpl
 * @see br.gov.demoiselle.portal.evento.model.EventoParticipante
 * @see br.gov.demoiselle.portal.evento.model.EventoParticipanteModel
 * @generated
 */
public class EventoParticipanteModelImpl extends BaseModelImpl<EventoParticipante>
	implements EventoParticipanteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evento participante model instance should use the {@link br.gov.demoiselle.portal.evento.model.EventoParticipante} interface instead.
	 */
	public static final String TABLE_NAME = "demoiselle_EventoParticipante";
	public static final Object[][] TABLE_COLUMNS = {
			{ "eventoParticipanteId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "eventoId", Types.BIGINT },
			{ "nome", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "instituicaoEmpresa", Types.VARCHAR },
			{ "conviteEnviado", Types.BOOLEAN },
			{ "certificadoImpresso", Types.BOOLEAN },
			{ "inscricaoConfirmada", Types.BOOLEAN },
			{ "participacaoConfirmada", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table demoiselle_EventoParticipante (eventoParticipanteId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,eventoId LONG,nome VARCHAR(75) null,email VARCHAR(75) null,instituicaoEmpresa VARCHAR(75) null,conviteEnviado BOOLEAN,certificadoImpresso BOOLEAN,inscricaoConfirmada BOOLEAN,participacaoConfirmada BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table demoiselle_EventoParticipante";
	public static final String ORDER_BY_JPQL = " ORDER BY eventoParticipante.eventoId ASC, eventoParticipante.nome ASC";
	public static final String ORDER_BY_SQL = " ORDER BY demoiselle_EventoParticipante.eventoId ASC, demoiselle_EventoParticipante.nome ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.gov.demoiselle.portal.evento.model.EventoParticipante"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.gov.demoiselle.portal.evento.model.EventoParticipante"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.gov.demoiselle.portal.evento.model.EventoParticipante"),
			true);
	public static long EMAIL_COLUMN_BITMASK = 1L;
	public static long EVENTOID_COLUMN_BITMASK = 2L;
	public static long NOME_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.gov.demoiselle.portal.evento.model.EventoParticipante"));

	public EventoParticipanteModelImpl() {
	}

	public long getPrimaryKey() {
		return _eventoParticipanteId;
	}

	public void setPrimaryKey(long primaryKey) {
		setEventoParticipanteId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_eventoParticipanteId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return EventoParticipante.class;
	}

	public String getModelClassName() {
		return EventoParticipante.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("eventoParticipanteId", getEventoParticipanteId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("eventoId", getEventoId());
		attributes.put("nome", getNome());
		attributes.put("email", getEmail());
		attributes.put("instituicaoEmpresa", getInstituicaoEmpresa());
		attributes.put("conviteEnviado", getConviteEnviado());
		attributes.put("certificadoImpresso", getCertificadoImpresso());
		attributes.put("inscricaoConfirmada", getInscricaoConfirmada());
		attributes.put("participacaoConfirmada", getParticipacaoConfirmada());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long eventoParticipanteId = (Long)attributes.get("eventoParticipanteId");

		if (eventoParticipanteId != null) {
			setEventoParticipanteId(eventoParticipanteId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long eventoId = (Long)attributes.get("eventoId");

		if (eventoId != null) {
			setEventoId(eventoId);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String instituicaoEmpresa = (String)attributes.get("instituicaoEmpresa");

		if (instituicaoEmpresa != null) {
			setInstituicaoEmpresa(instituicaoEmpresa);
		}

		Boolean conviteEnviado = (Boolean)attributes.get("conviteEnviado");

		if (conviteEnviado != null) {
			setConviteEnviado(conviteEnviado);
		}

		Boolean certificadoImpresso = (Boolean)attributes.get(
				"certificadoImpresso");

		if (certificadoImpresso != null) {
			setCertificadoImpresso(certificadoImpresso);
		}

		Boolean inscricaoConfirmada = (Boolean)attributes.get(
				"inscricaoConfirmada");

		if (inscricaoConfirmada != null) {
			setInscricaoConfirmada(inscricaoConfirmada);
		}

		Boolean participacaoConfirmada = (Boolean)attributes.get(
				"participacaoConfirmada");

		if (participacaoConfirmada != null) {
			setParticipacaoConfirmada(participacaoConfirmada);
		}
	}

	public long getEventoParticipanteId() {
		return _eventoParticipanteId;
	}

	public void setEventoParticipanteId(long eventoParticipanteId) {
		_eventoParticipanteId = eventoParticipanteId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getEventoId() {
		return _eventoId;
	}

	public void setEventoId(long eventoId) {
		_columnBitmask = -1L;

		if (!_setOriginalEventoId) {
			_setOriginalEventoId = true;

			_originalEventoId = _eventoId;
		}

		_eventoId = eventoId;
	}

	public long getOriginalEventoId() {
		return _originalEventoId;
	}

	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	public void setNome(String nome) {
		_columnBitmask = -1L;

		if (_originalNome == null) {
			_originalNome = _nome;
		}

		_nome = nome;
	}

	public String getOriginalNome() {
		return GetterUtil.getString(_originalNome);
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_columnBitmask |= EMAIL_COLUMN_BITMASK;

		if (_originalEmail == null) {
			_originalEmail = _email;
		}

		_email = email;
	}

	public String getOriginalEmail() {
		return GetterUtil.getString(_originalEmail);
	}

	public String getInstituicaoEmpresa() {
		if (_instituicaoEmpresa == null) {
			return StringPool.BLANK;
		}
		else {
			return _instituicaoEmpresa;
		}
	}

	public void setInstituicaoEmpresa(String instituicaoEmpresa) {
		_instituicaoEmpresa = instituicaoEmpresa;
	}

	public boolean getConviteEnviado() {
		return _conviteEnviado;
	}

	public boolean isConviteEnviado() {
		return _conviteEnviado;
	}

	public void setConviteEnviado(boolean conviteEnviado) {
		_conviteEnviado = conviteEnviado;
	}

	public boolean getCertificadoImpresso() {
		return _certificadoImpresso;
	}

	public boolean isCertificadoImpresso() {
		return _certificadoImpresso;
	}

	public void setCertificadoImpresso(boolean certificadoImpresso) {
		_certificadoImpresso = certificadoImpresso;
	}

	public boolean getInscricaoConfirmada() {
		return _inscricaoConfirmada;
	}

	public boolean isInscricaoConfirmada() {
		return _inscricaoConfirmada;
	}

	public void setInscricaoConfirmada(boolean inscricaoConfirmada) {
		_inscricaoConfirmada = inscricaoConfirmada;
	}

	public boolean getParticipacaoConfirmada() {
		return _participacaoConfirmada;
	}

	public boolean isParticipacaoConfirmada() {
		return _participacaoConfirmada;
	}

	public void setParticipacaoConfirmada(boolean participacaoConfirmada) {
		_participacaoConfirmada = participacaoConfirmada;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EventoParticipante.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventoParticipante toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (EventoParticipante)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EventoParticipanteImpl eventoParticipanteImpl = new EventoParticipanteImpl();

		eventoParticipanteImpl.setEventoParticipanteId(getEventoParticipanteId());
		eventoParticipanteImpl.setCompanyId(getCompanyId());
		eventoParticipanteImpl.setUserId(getUserId());
		eventoParticipanteImpl.setCreateDate(getCreateDate());
		eventoParticipanteImpl.setModifiedDate(getModifiedDate());
		eventoParticipanteImpl.setEventoId(getEventoId());
		eventoParticipanteImpl.setNome(getNome());
		eventoParticipanteImpl.setEmail(getEmail());
		eventoParticipanteImpl.setInstituicaoEmpresa(getInstituicaoEmpresa());
		eventoParticipanteImpl.setConviteEnviado(getConviteEnviado());
		eventoParticipanteImpl.setCertificadoImpresso(getCertificadoImpresso());
		eventoParticipanteImpl.setInscricaoConfirmada(getInscricaoConfirmada());
		eventoParticipanteImpl.setParticipacaoConfirmada(getParticipacaoConfirmada());

		eventoParticipanteImpl.resetOriginalValues();

		return eventoParticipanteImpl;
	}

	public int compareTo(EventoParticipante eventoParticipante) {
		int value = 0;

		if (getEventoId() < eventoParticipante.getEventoId()) {
			value = -1;
		}
		else if (getEventoId() > eventoParticipante.getEventoId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getNome().compareTo(eventoParticipante.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EventoParticipante eventoParticipante = null;

		try {
			eventoParticipante = (EventoParticipante)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = eventoParticipante.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EventoParticipanteModelImpl eventoParticipanteModelImpl = this;

		eventoParticipanteModelImpl._originalEventoId = eventoParticipanteModelImpl._eventoId;

		eventoParticipanteModelImpl._setOriginalEventoId = false;

		eventoParticipanteModelImpl._originalNome = eventoParticipanteModelImpl._nome;

		eventoParticipanteModelImpl._originalEmail = eventoParticipanteModelImpl._email;

		eventoParticipanteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventoParticipante> toCacheModel() {
		EventoParticipanteCacheModel eventoParticipanteCacheModel = new EventoParticipanteCacheModel();

		eventoParticipanteCacheModel.eventoParticipanteId = getEventoParticipanteId();

		eventoParticipanteCacheModel.companyId = getCompanyId();

		eventoParticipanteCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			eventoParticipanteCacheModel.createDate = createDate.getTime();
		}
		else {
			eventoParticipanteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eventoParticipanteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eventoParticipanteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eventoParticipanteCacheModel.eventoId = getEventoId();

		eventoParticipanteCacheModel.nome = getNome();

		String nome = eventoParticipanteCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			eventoParticipanteCacheModel.nome = null;
		}

		eventoParticipanteCacheModel.email = getEmail();

		String email = eventoParticipanteCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			eventoParticipanteCacheModel.email = null;
		}

		eventoParticipanteCacheModel.instituicaoEmpresa = getInstituicaoEmpresa();

		String instituicaoEmpresa = eventoParticipanteCacheModel.instituicaoEmpresa;

		if ((instituicaoEmpresa != null) && (instituicaoEmpresa.length() == 0)) {
			eventoParticipanteCacheModel.instituicaoEmpresa = null;
		}

		eventoParticipanteCacheModel.conviteEnviado = getConviteEnviado();

		eventoParticipanteCacheModel.certificadoImpresso = getCertificadoImpresso();

		eventoParticipanteCacheModel.inscricaoConfirmada = getInscricaoConfirmada();

		eventoParticipanteCacheModel.participacaoConfirmada = getParticipacaoConfirmada();

		return eventoParticipanteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{eventoParticipanteId=");
		sb.append(getEventoParticipanteId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", eventoId=");
		sb.append(getEventoId());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", instituicaoEmpresa=");
		sb.append(getInstituicaoEmpresa());
		sb.append(", conviteEnviado=");
		sb.append(getConviteEnviado());
		sb.append(", certificadoImpresso=");
		sb.append(getCertificadoImpresso());
		sb.append(", inscricaoConfirmada=");
		sb.append(getInscricaoConfirmada());
		sb.append(", participacaoConfirmada=");
		sb.append(getParticipacaoConfirmada());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("br.gov.demoiselle.portal.evento.model.EventoParticipante");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>eventoParticipanteId</column-name><column-value><![CDATA[");
		sb.append(getEventoParticipanteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventoId</column-name><column-value><![CDATA[");
		sb.append(getEventoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>instituicaoEmpresa</column-name><column-value><![CDATA[");
		sb.append(getInstituicaoEmpresa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>conviteEnviado</column-name><column-value><![CDATA[");
		sb.append(getConviteEnviado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificadoImpresso</column-name><column-value><![CDATA[");
		sb.append(getCertificadoImpresso());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscricaoConfirmada</column-name><column-value><![CDATA[");
		sb.append(getInscricaoConfirmada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>participacaoConfirmada</column-name><column-value><![CDATA[");
		sb.append(getParticipacaoConfirmada());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EventoParticipante.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			EventoParticipante.class
		};
	private long _eventoParticipanteId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _eventoId;
	private long _originalEventoId;
	private boolean _setOriginalEventoId;
	private String _nome;
	private String _originalNome;
	private String _email;
	private String _originalEmail;
	private String _instituicaoEmpresa;
	private boolean _conviteEnviado;
	private boolean _certificadoImpresso;
	private boolean _inscricaoConfirmada;
	private boolean _participacaoConfirmada;
	private long _columnBitmask;
	private EventoParticipante _escapedModelProxy;
}