/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.gov.demoiselle.portal.evento.model.impl;

import br.gov.demoiselle.portal.evento.model.EventoConvite;
import br.gov.demoiselle.portal.evento.model.EventoConviteModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EventoConvite service. Represents a row in the &quot;demoiselle_EventoConvite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.gov.demoiselle.portal.evento.model.EventoConviteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventoConviteImpl}.
 * </p>
 *
 * @author Clovis Lemes Ferreira Junior
 * @see EventoConviteImpl
 * @see br.gov.demoiselle.portal.evento.model.EventoConvite
 * @see br.gov.demoiselle.portal.evento.model.EventoConviteModel
 * @generated
 */
public class EventoConviteModelImpl extends BaseModelImpl<EventoConvite>
	implements EventoConviteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evento convite model instance should use the {@link br.gov.demoiselle.portal.evento.model.EventoConvite} interface instead.
	 */
	public static final String TABLE_NAME = "demoiselle_EventoConvite";
	public static final Object[][] TABLE_COLUMNS = {
			{ "eventoConviteId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "eventoId", Types.BIGINT },
			{ "textoConvite", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table demoiselle_EventoConvite (eventoConviteId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,eventoId LONG,textoConvite VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table demoiselle_EventoConvite";
	public static final String ORDER_BY_JPQL = " ORDER BY eventoConvite.eventoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY demoiselle_EventoConvite.eventoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.gov.demoiselle.portal.evento.model.EventoConvite"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.gov.demoiselle.portal.evento.model.EventoConvite"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.gov.demoiselle.portal.evento.model.EventoConvite"),
			true);
	public static long EVENTOID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.gov.demoiselle.portal.evento.model.EventoConvite"));

	public EventoConviteModelImpl() {
	}

	public long getPrimaryKey() {
		return _eventoConviteId;
	}

	public void setPrimaryKey(long primaryKey) {
		setEventoConviteId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_eventoConviteId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return EventoConvite.class;
	}

	public String getModelClassName() {
		return EventoConvite.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("eventoConviteId", getEventoConviteId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("eventoId", getEventoId());
		attributes.put("textoConvite", getTextoConvite());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long eventoConviteId = (Long)attributes.get("eventoConviteId");

		if (eventoConviteId != null) {
			setEventoConviteId(eventoConviteId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long eventoId = (Long)attributes.get("eventoId");

		if (eventoId != null) {
			setEventoId(eventoId);
		}

		String textoConvite = (String)attributes.get("textoConvite");

		if (textoConvite != null) {
			setTextoConvite(textoConvite);
		}
	}

	public long getEventoConviteId() {
		return _eventoConviteId;
	}

	public void setEventoConviteId(long eventoConviteId) {
		_eventoConviteId = eventoConviteId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getEventoId() {
		return _eventoId;
	}

	public void setEventoId(long eventoId) {
		_columnBitmask = -1L;

		if (!_setOriginalEventoId) {
			_setOriginalEventoId = true;

			_originalEventoId = _eventoId;
		}

		_eventoId = eventoId;
	}

	public long getOriginalEventoId() {
		return _originalEventoId;
	}

	public String getTextoConvite() {
		if (_textoConvite == null) {
			return StringPool.BLANK;
		}
		else {
			return _textoConvite;
		}
	}

	public void setTextoConvite(String textoConvite) {
		_textoConvite = textoConvite;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EventoConvite.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventoConvite toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (EventoConvite)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EventoConviteImpl eventoConviteImpl = new EventoConviteImpl();

		eventoConviteImpl.setEventoConviteId(getEventoConviteId());
		eventoConviteImpl.setCompanyId(getCompanyId());
		eventoConviteImpl.setUserId(getUserId());
		eventoConviteImpl.setCreateDate(getCreateDate());
		eventoConviteImpl.setModifiedDate(getModifiedDate());
		eventoConviteImpl.setEventoId(getEventoId());
		eventoConviteImpl.setTextoConvite(getTextoConvite());

		eventoConviteImpl.resetOriginalValues();

		return eventoConviteImpl;
	}

	public int compareTo(EventoConvite eventoConvite) {
		int value = 0;

		if (getEventoId() < eventoConvite.getEventoId()) {
			value = -1;
		}
		else if (getEventoId() > eventoConvite.getEventoId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EventoConvite eventoConvite = null;

		try {
			eventoConvite = (EventoConvite)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = eventoConvite.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EventoConviteModelImpl eventoConviteModelImpl = this;

		eventoConviteModelImpl._originalEventoId = eventoConviteModelImpl._eventoId;

		eventoConviteModelImpl._setOriginalEventoId = false;

		eventoConviteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventoConvite> toCacheModel() {
		EventoConviteCacheModel eventoConviteCacheModel = new EventoConviteCacheModel();

		eventoConviteCacheModel.eventoConviteId = getEventoConviteId();

		eventoConviteCacheModel.companyId = getCompanyId();

		eventoConviteCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			eventoConviteCacheModel.createDate = createDate.getTime();
		}
		else {
			eventoConviteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eventoConviteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eventoConviteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eventoConviteCacheModel.eventoId = getEventoId();

		eventoConviteCacheModel.textoConvite = getTextoConvite();

		String textoConvite = eventoConviteCacheModel.textoConvite;

		if ((textoConvite != null) && (textoConvite.length() == 0)) {
			eventoConviteCacheModel.textoConvite = null;
		}

		return eventoConviteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{eventoConviteId=");
		sb.append(getEventoConviteId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", eventoId=");
		sb.append(getEventoId());
		sb.append(", textoConvite=");
		sb.append(getTextoConvite());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("br.gov.demoiselle.portal.evento.model.EventoConvite");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>eventoConviteId</column-name><column-value><![CDATA[");
		sb.append(getEventoConviteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventoId</column-name><column-value><![CDATA[");
		sb.append(getEventoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>textoConvite</column-name><column-value><![CDATA[");
		sb.append(getTextoConvite());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EventoConvite.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			EventoConvite.class
		};
	private long _eventoConviteId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _eventoId;
	private long _originalEventoId;
	private boolean _setOriginalEventoId;
	private String _textoConvite;
	private long _columnBitmask;
	private EventoConvite _escapedModelProxy;
}