/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.gov.demoiselle.portal.evento.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventoConvite service. Represents a row in the &quot;demoiselle_EventoConvite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.demoiselle.portal.evento.model.impl.EventoConviteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.demoiselle.portal.evento.model.impl.EventoConviteImpl}.
 * </p>
 *
 * @author Clovis Lemes Ferreira Junior
 * @see EventoConvite
 * @see br.gov.demoiselle.portal.evento.model.impl.EventoConviteImpl
 * @see br.gov.demoiselle.portal.evento.model.impl.EventoConviteModelImpl
 * @generated
 */
public interface EventoConviteModel extends BaseModel<EventoConvite> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evento convite model instance should use the {@link EventoConvite} interface instead.
	 */

	/**
	 * Returns the primary key of this evento convite.
	 *
	 * @return the primary key of this evento convite
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evento convite.
	 *
	 * @param primaryKey the primary key of this evento convite
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evento convite ID of this evento convite.
	 *
	 * @return the evento convite ID of this evento convite
	 */
	public long getEventoConviteId();

	/**
	 * Sets the evento convite ID of this evento convite.
	 *
	 * @param eventoConviteId the evento convite ID of this evento convite
	 */
	public void setEventoConviteId(long eventoConviteId);

	/**
	 * Returns the company ID of this evento convite.
	 *
	 * @return the company ID of this evento convite
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this evento convite.
	 *
	 * @param companyId the company ID of this evento convite
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this evento convite.
	 *
	 * @return the user ID of this evento convite
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this evento convite.
	 *
	 * @param userId the user ID of this evento convite
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evento convite.
	 *
	 * @return the user uuid of this evento convite
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this evento convite.
	 *
	 * @param userUuid the user uuid of this evento convite
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this evento convite.
	 *
	 * @return the create date of this evento convite
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this evento convite.
	 *
	 * @param createDate the create date of this evento convite
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this evento convite.
	 *
	 * @return the modified date of this evento convite
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this evento convite.
	 *
	 * @param modifiedDate the modified date of this evento convite
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the evento ID of this evento convite.
	 *
	 * @return the evento ID of this evento convite
	 */
	public long getEventoId();

	/**
	 * Sets the evento ID of this evento convite.
	 *
	 * @param eventoId the evento ID of this evento convite
	 */
	public void setEventoId(long eventoId);

	/**
	 * Returns the texto convite of this evento convite.
	 *
	 * @return the texto convite of this evento convite
	 */
	@AutoEscape
	public String getTextoConvite();

	/**
	 * Sets the texto convite of this evento convite.
	 *
	 * @param textoConvite the texto convite of this evento convite
	 */
	public void setTextoConvite(String textoConvite);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EventoConvite eventoConvite);

	public int hashCode();

	public CacheModel<EventoConvite> toCacheModel();

	public EventoConvite toEscapedModel();

	public String toString();

	public String toXmlString();
}